server {
    listen 80 default_server;
    root /usr/share/nginx/html;
    index index.html;

    location /zawmoewin { # သင့် Xray Path နဲ့ တူရပါမယ်
        proxy_redirect off;
        proxy_pass http://127.0.0.1:10000; # Xray port
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
    }
}

